<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menus')->delete();
        
        \DB::table('menus')->insert(array (
            0 => 
            array (
                'id' => 1,
                'parent_id' => NULL,
                'name' => 'Dashboard',
                'bn_name' => 'ড্যাশবোর্ড',
                'system_name' => 'Dashboard',
                'route_name' => 'dashboard',
                'icon' => 'uil-home-alt',
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-03-19 14:04:30',
                'updated_at' => '2023-11-12 12:23:41',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'parent_id' => NULL,
                'name' => 'User Management',
                'bn_name' => 'ইউজার ম্যানেজমেন্ট',
                'system_name' => 'User Management',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-03-19 18:06:39',
                'updated_at' => '2023-11-12 12:23:41',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'parent_id' => 2,
                'name' => 'User',
                'bn_name' => 'ইউজার',
                'system_name' => 'User',
                'route_name' => 'user.index',
                'icon' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-03-19 18:08:09',
                'updated_at' => '2023-03-31 18:10:57',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 5,
                'parent_id' => 2,
                'name' => 'Role',
                'bn_name' => 'রোল',
                'system_name' => 'Role',
                'route_name' => 'role.index',
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-03-19 18:17:21',
                'updated_at' => '2023-03-31 18:11:32',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 25,
                'parent_id' => NULL,
                'name' => 'Menu Management',
                'bn_name' => 'মেন্যু ম্যানেজমেন্ট',
                'system_name' => 'Menu Management',
                'route_name' => '',
                'icon' => NULL,
                'order_by' => 3,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-04-03 10:38:48',
                'updated_at' => '2023-04-03 10:38:48',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 26,
                'parent_id' => 25,
                'name' => 'Menu',
                'bn_name' => 'মেন্যু',
                'system_name' => 'Menu',
                'route_name' => 'menu.index',
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-04-03 10:39:32',
                'updated_at' => '2023-04-03 10:39:32',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 27,
                'parent_id' => NULL,
                'name' => 'About Institute',
                'bn_name' => 'প্রতিষ্ঠান সম্পর্কে',
                'system_name' => 'About Institute',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 4,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-11 13:35:23',
                'updated_at' => '2023-11-12 12:23:41',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 28,
                'parent_id' => 27,
                'name' => 'Pages',
                'bn_name' => 'পেইজ',
                'system_name' => 'Pages',
                'route_name' => 'pages.index',
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-11 13:35:49',
                'updated_at' => '2023-06-11 13:36:35',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 29,
                'parent_id' => NULL,
                'name' => 'Administrator Info.',
                'bn_name' => 'প্রশাসনিক তথ্য',
                'system_name' => 'Administrator Info.',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 5,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-11 13:37:43',
                'updated_at' => '2023-11-12 12:23:41',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 30,
                'parent_id' => 29,
                'name' => 'Administrative Messages',
                'bn_name' => 'প্রশাসনিক বার্তা',
                'system_name' => 'Principle',
                'route_name' => 'principle.index',
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-11 13:38:49',
                'updated_at' => '2023-12-03 10:49:46',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 31,
                'parent_id' => NULL,
                'name' => 'Gallery',
                'bn_name' => 'গ্যালারি',
                'system_name' => 'Gallery',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 6,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-11 13:54:20',
                'updated_at' => '2023-11-12 12:23:41',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 32,
                'parent_id' => 78,
                'name' => 'Photo Gallary',
                'bn_name' => 'ফটো গ্যালারি',
                'system_name' => 'Photo Gallary',
                'route_name' => 'photogallerys.index',
                'icon' => NULL,
                'order_by' => 5,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-11 13:54:53',
                'updated_at' => '2023-12-10 04:51:21',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 33,
                'parent_id' => 78,
                'name' => 'Video Gallary',
                'bn_name' => 'ভিডিও গ্যালারি',
                'system_name' => 'Video Gallary',
                'route_name' => 'videogallerys.index',
                'icon' => NULL,
                'order_by' => 4,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-11 13:55:31',
                'updated_at' => '2023-12-10 04:51:21',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 36,
                'parent_id' => NULL,
                'name' => 'Useful Link',
                'bn_name' => 'লিংক',
                'system_name' => 'Useful Link',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 7,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-11 14:09:21',
                'updated_at' => '2023-11-12 12:23:41',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 37,
                'parent_id' => 78,
                'name' => 'Link',
                'bn_name' => 'লিংক',
                'system_name' => 'Link',
                'route_name' => 'usefullink.index',
                'icon' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-11 14:09:57',
                'updated_at' => '2023-06-11 14:09:57',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 38,
                'parent_id' => 29,
                'name' => 'Add Members',
                'bn_name' => 'সদস্য যোগ করুন',
                'system_name' => 'Add Members',
                'route_name' => 'members.index',
                'icon' => NULL,
                'order_by' => 3,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-11 14:28:27',
                'updated_at' => '2023-07-16 05:09:11',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 39,
                'parent_id' => NULL,
                'name' => 'Academic Info.',
                'bn_name' => 'একাডেমিক তথ্যসমূহ',
                'system_name' => 'Academic Info.',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 8,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-13 13:34:38',
                'updated_at' => '2023-11-12 12:23:41',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 40,
                'parent_id' => 27,
                'name' => 'Academic Calender',
                'bn_name' => 'শিক্ষা বর্ষপঞ্জি',
                'system_name' => 'Academic Calender',
                'route_name' => 'academiccalender.index',
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-13 13:35:34',
                'updated_at' => '2023-06-13 13:35:34',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 41,
                'parent_id' => 27,
                'name' => 'Class Routine',
                'bn_name' => 'ক্লাস রুটিন',
                'system_name' => 'Class Routine',
                'route_name' => 'classroutine.index',
                'icon' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-13 13:36:26',
                'updated_at' => '2023-06-13 13:36:26',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 42,
                'parent_id' => 27,
                'name' => 'Holiday List',
                'bn_name' => 'ছুটির দিন',
                'system_name' => 'Holiday List',
                'route_name' => 'holidaylist.index',
                'icon' => NULL,
                'order_by' => 3,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-13 13:38:27',
                'updated_at' => '2023-06-13 13:38:27',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 50,
                'parent_id' => 29,
                'name' => 'Admission Info.',
                'bn_name' => 'ভর্তি সংক্রান্ত তথ্য',
                'system_name' => 'Admission Info.',
                'route_name' => 'admissioninfo.index',
                'icon' => NULL,
                'order_by' => 7,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-13 14:24:49',
                'updated_at' => '2023-12-14 06:14:08',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 51,
                'parent_id' => NULL,
                'name' => 'Class Info.',
                'bn_name' => 'শ্রেণী সম্পর্কিত তথ্য',
                'system_name' => 'Class Info.',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 9,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-14 05:54:43',
                'updated_at' => '2023-11-12 12:23:41',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 52,
                'parent_id' => 51,
                'name' => 'Add Class',
                'bn_name' => 'শ্রেণী যোগ করুন',
                'system_name' => 'Add Class',
                'route_name' => 'addclass.index',
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-14 05:55:09',
                'updated_at' => '2023-06-14 05:55:09',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 53,
                'parent_id' => 51,
                'name' => 'Add Group',
                'bn_name' => 'গ্রুপ যোগ করুন',
                'system_name' => 'Add Group',
                'route_name' => 'addgroup.index',
                'icon' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-14 05:55:42',
                'updated_at' => '2023-06-14 05:55:42',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 54,
                'parent_id' => 51,
                'name' => 'Add Section',
                'bn_name' => 'বিভাগ যোগ করুন',
                'system_name' => 'Add Section',
                'route_name' => 'addsection.index',
                'icon' => NULL,
                'order_by' => 3,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-14 05:56:11',
                'updated_at' => '2023-11-09 05:01:19',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 55,
                'parent_id' => NULL,
                'name' => 'Exam Info',
                'bn_name' => 'পরীক্ষা সংক্রান্ত তথ্য',
                'system_name' => 'Exam Info',
                'route_name' => 'examinfo',
                'icon' => NULL,
                'order_by' => 10,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-15 05:53:10',
                'updated_at' => '2023-11-12 12:23:41',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 56,
                'parent_id' => 55,
                'name' => 'Exam Routine',
                'bn_name' => 'পরীক্ষার রুটিন',
                'system_name' => 'Exam Routine',
                'route_name' => 'examroutine.index',
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-15 05:54:02',
                'updated_at' => '2023-06-15 05:54:02',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 57,
                'parent_id' => 55,
                'name' => 'Syllabus',
                'bn_name' => 'সিলেবাস',
                'system_name' => 'Syllabus',
                'route_name' => 'syllabus.index',
                'icon' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-15 05:54:32',
                'updated_at' => '2023-06-15 05:54:32',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 58,
                'parent_id' => 55,
                'name' => 'Lesson Plan',
                'bn_name' => 'পাঠ পরিকল্পনা',
                'system_name' => 'Lesson Plan',
                'route_name' => 'lessonplan.index',
                'icon' => NULL,
                'order_by' => 3,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-15 05:54:59',
                'updated_at' => '2023-06-15 05:54:59',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 59,
                'parent_id' => 55,
                'name' => 'Suggestion',
                'bn_name' => 'সাজেশন্স',
                'system_name' => 'Suggestion',
                'route_name' => 'suggestion.index',
                'icon' => NULL,
                'order_by' => 4,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-15 05:55:51',
                'updated_at' => '2023-06-15 05:55:51',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 60,
                'parent_id' => NULL,
                'name' => 'Teacher & Staff info.',
                'bn_name' => 'শিক্ষক - কর্মচারীদের তথ্য',
                'system_name' => 'Teacher & Staff info.',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 11,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-15 06:30:54',
                'updated_at' => '2023-11-12 12:23:41',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 61,
                'parent_id' => 60,
                'name' => 'Department',
                'bn_name' => 'বিভাগ যুক্ত করুন',
                'system_name' => 'Department',
                'route_name' => 'department.index',
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-15 06:31:38',
                'updated_at' => '2023-06-15 06:31:38',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 62,
                'parent_id' => 60,
                'name' => 'Teacher & Staff',
                'bn_name' => 'শিক্ষক - কর্মচারী যুক্ত করুন',
                'system_name' => 'Teacher & Staff',
                'route_name' => 'teacherstaff.index',
                'icon' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-15 06:32:10',
                'updated_at' => '2023-06-15 06:32:10',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 63,
                'parent_id' => 78,
                'name' => 'Website Setting',
                'bn_name' => 'সেটিংস',
                'system_name' => 'Website Setting',
                'route_name' => 'setting.create',
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-18 05:29:49',
                'updated_at' => '2023-09-23 09:50:25',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 64,
                'parent_id' => NULL,
                'name' => 'Registration Info',
                'bn_name' => 'অ্যাডমিশন তথ্য',
                'system_name' => 'Admission Info',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 18,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-27 09:20:02',
                'updated_at' => '2023-12-17 05:37:52',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 65,
                'parent_id' => 64,
                'name' => 'View Admission Data',
                'bn_name' => 'অ্যাডমিশন তথ্য',
                'system_name' => 'View Admission Data',
                'route_name' => 'admission_info.index',
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-27 09:20:55',
                'updated_at' => '2023-06-27 09:20:56',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 66,
                'parent_id' => 29,
                'name' => 'Vice Principal Message',
                'bn_name' => 'উপাধ্যক্ষ বার্তা',
                'system_name' => 'Vice Principal Message',
                'route_name' => 'vice_principal_message.index',
                'icon' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-07-16 05:09:11',
                'updated_at' => '2023-07-16 05:09:12',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 67,
                'parent_id' => 27,
                'name' => 'Teaching permission and recognition',
                'bn_name' => 'পাঠাদানের অনুমতি ও স্বীকৃতি',
                'system_name' => 'Teaching permission and recognition',
                'route_name' => 'teaching_permission.index',
                'icon' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-09-10 09:47:13',
                'updated_at' => '2023-09-10 09:47:14',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 68,
                'parent_id' => 27,
                'name' => 'MPO/Nationalization Info',
                'bn_name' => 'এমপিও/জাতীয়করণ তথ্য',
                'system_name' => 'MPO_Nationalization Info',
                'route_name' => 'mpo_nationalization.index',
                'icon' => NULL,
                'order_by' => 3,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-09-10 09:48:59',
                'updated_at' => '2023-09-10 09:48:59',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 78,
                'parent_id' => NULL,
                'name' => 'Project Settings',
                'bn_name' => 'প্রজেক্ট সেটিংস',
                'system_name' => 'Project Settings',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 32,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-09-23 09:50:25',
                'updated_at' => '2023-12-17 05:37:53',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 80,
                'parent_id' => 78,
                'name' => 'Backup',
                'bn_name' => 'ব্যাকআপ',
                'system_name' => 'Backup',
                'route_name' => 'backup.index',
                'icon' => NULL,
                'order_by' => 6,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-09-23 09:56:24',
                'updated_at' => '2023-12-10 04:51:21',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 81,
                'parent_id' => 29,
                'name' => 'Notices',
                'bn_name' => 'নোটিশ',
                'system_name' => 'Notices',
                'route_name' => 'notices.index',
                'icon' => NULL,
                'order_by' => 4,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-10-04 05:33:50',
                'updated_at' => '2023-10-04 05:33:50',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 82,
                'parent_id' => NULL,
                'name' => 'Student Panel',
                'bn_name' => 'শিক্ষার্থী প্যানেল',
                'system_name' => 'student_info',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 13,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-10-31 11:31:10',
                'updated_at' => '2023-12-04 07:05:33',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 83,
                'parent_id' => 82,
                'name' => 'Add Student Info',
                'bn_name' => 'শিক্ষার্থী তথ্য যোগ করুন',
                'system_name' => 'student info',
                'route_name' => 'student_info.index',
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-10-31 11:33:10',
                'updated_at' => '2023-12-04 07:07:00',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 84,
                'parent_id' => NULL,
                'name' => 'Subject Info',
                'bn_name' => 'বিষয় সম্পর্কিত তথ্য',
                'system_name' => 'Subject Info',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 14,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-11-05 06:07:37',
                'updated_at' => '2023-11-12 12:23:41',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 85,
                'parent_id' => 84,
                'name' => 'Add Subject',
                'bn_name' => 'বিষয় যোগ করুন',
                'system_name' => 'Add Subject',
                'route_name' => 'add_subject.index',
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-11-05 06:08:58',
                'updated_at' => '2023-11-05 06:08:58',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 86,
                'parent_id' => 84,
                'name' => 'Add Subject Part',
                'bn_name' => 'বিষয়ের পার্ট যোগ করুন',
                'system_name' => 'Add Subject Part',
                'route_name' => 'add_subject_part.index',
                'icon' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-11-05 11:09:17',
                'updated_at' => '2023-11-05 11:09:17',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 87,
                'parent_id' => 84,
                'name' => 'Mark Distribution',
                'bn_name' => 'নাম্বার বন্টন',
                'system_name' => 'Mark Distribution',
                'route_name' => 'mark_distribution.index',
                'icon' => NULL,
                'order_by' => 3,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-11-06 06:59:16',
                'updated_at' => '2023-11-06 06:59:16',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 88,
                'parent_id' => NULL,
                'name' => 'Online Education',
                'bn_name' => 'অনলাইন শিক্ষা',
                'system_name' => 'Online Education',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 16,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-11-09 04:42:07',
                'updated_at' => '2023-12-17 05:37:53',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 89,
                'parent_id' => 88,
                'name' => 'Online Lecture Upload',
                'bn_name' => 'অনলাইন লেকচার আপলোড',
                'system_name' => 'Online Lecture Upload',
                'route_name' => 'online_lecture_upload.index',
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-11-09 04:42:57',
                'updated_at' => '2023-11-09 04:42:57',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 90,
                'parent_id' => 27,
                'name' => 'Upload Download File',
                'bn_name' => 'ডাউনলোড ফাইল আপলোড',
                'system_name' => 'Upload Download File',
                'route_name' => 'upload_download_file.index',
                'icon' => NULL,
                'order_by' => 7,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-11-11 17:19:32',
                'updated_at' => '2023-11-12 11:08:46',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 91,
                'parent_id' => NULL,
                'name' => 'Result Entry',
                'bn_name' => 'ফলাফল এন্ট্রি',
                'system_name' => 'Result Entry',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 17,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-11-12 12:18:37',
                'updated_at' => '2023-12-17 05:37:53',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 92,
                'parent_id' => 91,
                'name' => 'Add Marks',
                'bn_name' => 'মার্কস যোগ করুন',
                'system_name' => 'Add Marks',
                'route_name' => 'add_marks.index',
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-11-12 12:19:41',
                'updated_at' => '2023-11-12 12:19:41',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 93,
                'parent_id' => 91,
                'name' => 'View Marks',
                'bn_name' => 'মার্কস দেখুন',
                'system_name' => 'View Marks',
                'route_name' => 'view_marks.index',
                'icon' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-11-12 12:20:33',
                'updated_at' => '2023-11-12 12:20:34',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 94,
                'parent_id' => 91,
            'name' => 'View Total Subject Marks Entry(Student)',
                'bn_name' => 'মোট সাবজেক্ট মার্ক এন্ট্রি দেখুন',
            'system_name' => 'View Total Subject Marks Entry(Student)',
                'route_name' => 'view_total_subject_marks.index',
                'icon' => NULL,
                'order_by' => 3,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-11-12 12:21:48',
                'updated_at' => '2023-11-12 12:21:49',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 95,
                'parent_id' => 91,
                'name' => 'View Complete Subject Marks Entry',
                'bn_name' => 'সম্পূর্ণ বিষয় মার্ক এন্ট্রি দেখুন',
                'system_name' => 'View Complete Subject Marks Entry',
                'route_name' => 'view_completed_subject.index',
                'icon' => NULL,
                'order_by' => 4,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-11-12 12:22:51',
                'updated_at' => '2023-11-12 12:22:51',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 96,
                'parent_id' => 91,
            'name' => 'Generate Grade Point (GP)',
                'bn_name' => 'গ্রেড পয়েন্ট জেনারেট করুন',
            'system_name' => 'Generate Grade Point (GP)',
                'route_name' => 'generate_gpa.index',
                'icon' => NULL,
                'order_by' => 5,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-11-12 12:23:41',
                'updated_at' => '2023-11-12 12:25:25',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 97,
                'parent_id' => 91,
            'name' => 'Generate Grade Point Avg. (GPA)',
            'bn_name' => 'গ্রেড পয়েন্ট গড় তৈরি করুন (জিপিএ)',
            'system_name' => 'Generate Grade Point Avg. (GPA)',
                'route_name' => 'generate_grade_point.index',
                'icon' => NULL,
                'order_by' => 6,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-12-02 04:50:31',
                'updated_at' => '2023-12-02 04:50:31',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 98,
                'parent_id' => 55,
                'name' => 'Exam Type',
                'bn_name' => 'পরীক্ষার ধরণ',
                'system_name' => 'Exam Type',
                'route_name' => 'add_exam_type.index',
                'icon' => NULL,
                'order_by' => 4,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-12-02 05:28:10',
                'updated_at' => '2023-12-02 05:28:10',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 99,
                'parent_id' => 110,
                'name' => 'NOC',
                'bn_name' => 'অনাপত্তি সনদ',
                'system_name' => 'NOC',
                'route_name' => 'add_noc.index',
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-12-06 11:42:30',
                'updated_at' => '2023-12-17 05:38:50',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 100,
                'parent_id' => 78,
                'name' => 'Session',
                'bn_name' => 'সেশন',
                'system_name' => 'Session',
                'route_name' => 'session.index',
                'icon' => NULL,
                'order_by' => 3,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-12-10 04:51:21',
                'updated_at' => '2023-12-10 04:51:21',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 101,
                'parent_id' => 82,
                'name' => 'Registerd Student',
                'bn_name' => 'রেজিষ্ট্রেশনকৃত শিক্ষার্থী',
                'system_name' => 'Registerd Student',
                'route_name' => 'registered_student.index',
                'icon' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-12-10 10:38:21',
                'updated_at' => '2023-12-10 10:38:21',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 102,
                'parent_id' => NULL,
                'name' => 'Accounts Section',
                'bn_name' => 'অ্যাকাউন্টস সেকশন',
                'system_name' => 'Column',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 30,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-12-11 04:47:29',
                'updated_at' => '2023-12-17 05:37:53',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 103,
                'parent_id' => 102,
                'name' => 'Others Income Column',
                'bn_name' => 'অন্যান্য আয় কলাম',
                'system_name' => 'Others Income Column',
                'route_name' => 'others_income.index',
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-12-11 04:48:40',
                'updated_at' => '2023-12-13 17:19:53',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 104,
                'parent_id' => 102,
                'name' => 'Expense Column',
                'bn_name' => 'ব্যয় কলাম',
                'system_name' => 'Expense Column',
                'route_name' => 'expense_column.index',
                'icon' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-12-11 04:56:01',
                'updated_at' => '2023-12-11 04:56:01',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 105,
                'parent_id' => 102,
                'name' => 'Student Fee Collection Column',
                'bn_name' => 'শিক্ষার্থী ফি সংগ্রহ কলাম',
                'system_name' => 'Student Fee Collection Column',
                'route_name' => 'student_fee_column.index',
                'icon' => NULL,
                'order_by' => 3,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-12-11 05:43:55',
                'updated_at' => '2023-12-11 06:08:05',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 106,
                'parent_id' => 102,
                'name' => 'Add Income Expense Title',
                'bn_name' => 'আয় ব্যয়ের শিরোনাম যোগ করুন',
                'system_name' => 'Add Income Expense Title',
                'route_name' => 'income_expense.index',
                'icon' => NULL,
                'order_by' => 4,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-12-12 04:32:19',
                'updated_at' => '2023-12-12 04:32:19',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 107,
                'parent_id' => 102,
                'name' => 'Expense Entry',
                'bn_name' => 'ব্যয় যোগ করুন',
                'system_name' => 'Expense Entry',
                'route_name' => 'expense_entry.index',
                'icon' => NULL,
                'order_by' => 7,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-12-13 06:03:34',
                'updated_at' => '2023-12-13 17:22:18',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 108,
                'parent_id' => 102,
                'name' => 'Others Income Entry',
                'bn_name' => 'অন্যান্য আয় যোগ করুন',
                'system_name' => 'Others Income Entry',
                'route_name' => 'others_income_entry.index',
                'icon' => NULL,
                'order_by' => 5,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-12-13 17:22:18',
                'updated_at' => '2023-12-13 17:22:18',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 109,
                'parent_id' => 110,
                'name' => 'Position Details of the Institute',
                'bn_name' => 'প্রতিষ্ঠানের পদের বিবরণী',
                'system_name' => 'Position Details of the Institute',
                'route_name' => 'institute_position_details.index',
                'icon' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-12-14 06:14:08',
                'updated_at' => '2023-12-17 05:38:24',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 110,
                'parent_id' => NULL,
                'name' => 'Other Services',
                'bn_name' => 'অন্যান্য সেবা',
                'system_name' => 'Other Services',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 15,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-12-17 05:37:53',
                'updated_at' => '2023-12-17 05:37:53',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}