<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('permissions')->delete();
        
        \DB::table('permissions')->insert(array (
            0 => 
            array (
                'created_at' => '2023-03-19 16:25:23',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 1,
                'name' => 'Dashboard',
                'parent' => 'Dashboard',
                'status' => 1,
                'updated_at' => '2023-03-19 16:25:23',
            ),
            1 => 
            array (
                'created_at' => '2023-03-19 18:08:09',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 2,
                'name' => 'User List',
                'parent' => 'User',
                'status' => 1,
                'updated_at' => '2023-03-19 18:08:09',
            ),
            2 => 
            array (
                'created_at' => '2023-03-19 18:08:09',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 3,
                'name' => 'User Create',
                'parent' => 'User',
                'status' => 1,
                'updated_at' => '2023-03-19 18:08:09',
            ),
            3 => 
            array (
                'created_at' => '2023-03-19 18:08:09',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 4,
                'name' => 'User Edit',
                'parent' => 'User',
                'status' => 1,
                'updated_at' => '2023-03-19 18:08:09',
            ),
            4 => 
            array (
                'created_at' => '2023-03-19 18:08:09',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 5,
                'name' => 'User Delete',
                'parent' => 'User',
                'status' => 1,
                'updated_at' => '2023-03-19 18:08:09',
            ),
            5 => 
            array (
                'created_at' => '2023-03-19 18:08:09',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 6,
                'name' => 'User View',
                'parent' => 'User',
                'status' => 1,
                'updated_at' => '2023-03-19 18:08:09',
            ),
            6 => 
            array (
                'created_at' => '2023-03-19 18:08:09',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 7,
                'name' => 'User Print',
                'parent' => 'User',
                'status' => 1,
                'updated_at' => '2023-03-19 18:08:09',
            ),
            7 => 
            array (
                'created_at' => '2023-03-19 18:08:09',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 8,
                'name' => 'User Restore',
                'parent' => 'User',
                'status' => 1,
                'updated_at' => '2023-03-19 18:08:09',
            ),
            8 => 
            array (
                'created_at' => '2023-03-19 18:17:22',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 9,
                'name' => 'Role List',
                'parent' => 'Role',
                'status' => 1,
                'updated_at' => '2023-03-19 18:17:22',
            ),
            9 => 
            array (
                'created_at' => '2023-03-19 18:17:22',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 10,
                'name' => 'Role Create',
                'parent' => 'Role',
                'status' => 1,
                'updated_at' => '2023-03-19 18:17:22',
            ),
            10 => 
            array (
                'created_at' => '2023-03-19 18:17:22',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 11,
                'name' => 'Role Edit',
                'parent' => 'Role',
                'status' => 1,
                'updated_at' => '2023-03-19 18:17:22',
            ),
            11 => 
            array (
                'created_at' => '2023-03-19 18:17:22',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 12,
                'name' => 'Role Delete',
                'parent' => 'Role',
                'status' => 1,
                'updated_at' => '2023-03-19 18:17:22',
            ),
            12 => 
            array (
                'created_at' => '2023-03-19 18:17:22',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 13,
                'name' => 'Role View',
                'parent' => 'Role',
                'status' => 1,
                'updated_at' => '2023-03-19 18:17:22',
            ),
            13 => 
            array (
                'created_at' => '2023-03-19 18:17:22',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 14,
                'name' => 'Role Print',
                'parent' => 'Role',
                'status' => 1,
                'updated_at' => '2023-03-19 18:17:22',
            ),
            14 => 
            array (
                'created_at' => '2023-03-19 18:17:22',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 15,
                'name' => 'Role Restore',
                'parent' => 'Role',
                'status' => 1,
                'updated_at' => '2023-03-19 18:17:22',
            ),
            15 => 
            array (
                'created_at' => '2023-03-19 18:17:22',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 16,
                'name' => 'Role Permission',
                'parent' => 'Role',
                'status' => 1,
                'updated_at' => '2023-03-19 18:17:22',
            ),
            16 => 
            array (
                'created_at' => '2023-03-29 04:28:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 18,
                'name' => 'Apps Information List',
                'parent' => 'Apps Information',
                'status' => 1,
                'updated_at' => '2023-03-29 04:28:32',
            ),
            17 => 
            array (
                'created_at' => '2023-03-29 04:28:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 19,
                'name' => 'Apps Information Create',
                'parent' => 'Apps Information',
                'status' => 1,
                'updated_at' => '2023-03-29 04:28:32',
            ),
            18 => 
            array (
                'created_at' => '2023-03-29 04:28:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 20,
                'name' => 'Apps Information Edit',
                'parent' => 'Apps Information',
                'status' => 1,
                'updated_at' => '2023-03-29 04:28:32',
            ),
            19 => 
            array (
                'created_at' => '2023-03-29 04:28:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 21,
                'name' => 'Apps Information Delete',
                'parent' => 'Apps Information',
                'status' => 1,
                'updated_at' => '2023-03-29 04:28:32',
            ),
            20 => 
            array (
                'created_at' => '2023-03-29 04:28:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 22,
                'name' => 'Apps Information View',
                'parent' => 'Apps Information',
                'status' => 1,
                'updated_at' => '2023-03-29 04:28:32',
            ),
            21 => 
            array (
                'created_at' => '2023-03-29 04:28:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 23,
                'name' => 'Apps Information Print',
                'parent' => 'Apps Information',
                'status' => 1,
                'updated_at' => '2023-03-29 04:28:32',
            ),
            22 => 
            array (
                'created_at' => '2023-03-29 04:28:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 24,
                'name' => 'Apps Information Edit_history',
                'parent' => 'Apps Information',
                'status' => 1,
                'updated_at' => '2023-03-29 04:28:32',
            ),
            23 => 
            array (
                'created_at' => '2023-03-29 04:35:23',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 27,
                'name' => 'About Us Create',
                'parent' => 'About Us',
                'status' => 1,
                'updated_at' => '2023-03-29 04:35:23',
            ),
            24 => 
            array (
                'created_at' => '2023-03-29 04:35:23',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 28,
                'name' => 'About Us Edit',
                'parent' => 'About Us',
                'status' => 1,
                'updated_at' => '2023-03-29 04:35:23',
            ),
            25 => 
            array (
                'created_at' => '2023-03-29 04:35:23',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 29,
                'name' => 'About Us Delete',
                'parent' => 'About Us',
                'status' => 1,
                'updated_at' => '2023-03-29 04:35:23',
            ),
            26 => 
            array (
                'created_at' => '2023-03-29 04:35:23',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 30,
                'name' => 'About Us View',
                'parent' => 'About Us',
                'status' => 1,
                'updated_at' => '2023-03-29 04:35:23',
            ),
            27 => 
            array (
                'created_at' => '2023-03-29 04:35:23',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 31,
                'name' => 'About Us Print',
                'parent' => 'About Us',
                'status' => 1,
                'updated_at' => '2023-03-29 04:35:23',
            ),
            28 => 
            array (
                'created_at' => '2023-03-29 04:35:23',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 32,
                'name' => 'About Us Edit_history',
                'parent' => 'About Us',
                'status' => 1,
                'updated_at' => '2023-03-29 04:35:23',
            ),
            29 => 
            array (
                'created_at' => '2023-03-29 09:02:52',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 41,
                'name' => 'Website Info Edit_history',
                'parent' => 'Website Info',
                'status' => 1,
                'updated_at' => '2023-03-29 09:02:52',
            ),
            30 => 
            array (
                'created_at' => '2023-03-30 05:45:25',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 49,
                'name' => 'Photo Gallery Edit_history',
                'parent' => 'Photo Gallery',
                'status' => 1,
                'updated_at' => '2023-03-30 05:45:25',
            ),
            31 => 
            array (
                'created_at' => '2023-04-01 06:32:18',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 56,
                'name' => 'Services Edit_history',
                'parent' => 'Services',
                'status' => 1,
                'updated_at' => '2023-04-01 06:32:18',
            ),
            32 => 
            array (
                'created_at' => '2023-04-01 08:52:40',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 64,
                'name' => 'Project Info List',
                'parent' => 'Project Info',
                'status' => 1,
                'updated_at' => '2023-04-01 08:52:40',
            ),
            33 => 
            array (
                'created_at' => '2023-04-01 08:52:40',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 65,
                'name' => 'Project Info Create',
                'parent' => 'Project Info',
                'status' => 1,
                'updated_at' => '2023-04-01 08:52:40',
            ),
            34 => 
            array (
                'created_at' => '2023-04-01 08:52:40',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 66,
                'name' => 'Project Info Edit',
                'parent' => 'Project Info',
                'status' => 1,
                'updated_at' => '2023-04-01 08:52:40',
            ),
            35 => 
            array (
                'created_at' => '2023-04-01 08:52:40',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 67,
                'name' => 'Project Info Delete',
                'parent' => 'Project Info',
                'status' => 1,
                'updated_at' => '2023-04-01 08:52:40',
            ),
            36 => 
            array (
                'created_at' => '2023-04-01 08:52:40',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 68,
                'name' => 'Project Info View',
                'parent' => 'Project Info',
                'status' => 1,
                'updated_at' => '2023-04-01 08:52:40',
            ),
            37 => 
            array (
                'created_at' => '2023-04-01 08:52:40',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 69,
                'name' => 'Project Info Print',
                'parent' => 'Project Info',
                'status' => 1,
                'updated_at' => '2023-04-01 08:52:40',
            ),
            38 => 
            array (
                'created_at' => '2023-04-01 08:52:40',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 70,
                'name' => 'Project Info Edit_history',
                'parent' => 'Project Info',
                'status' => 1,
                'updated_at' => '2023-04-01 08:52:40',
            ),
            39 => 
            array (
                'created_at' => '2023-04-01 08:53:23',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 71,
                'name' => 'Project Category List',
                'parent' => 'Project Category',
                'status' => 1,
                'updated_at' => '2023-04-01 08:53:23',
            ),
            40 => 
            array (
                'created_at' => '2023-04-01 08:53:23',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 72,
                'name' => 'Project Category Create',
                'parent' => 'Project Category',
                'status' => 1,
                'updated_at' => '2023-04-01 08:53:23',
            ),
            41 => 
            array (
                'created_at' => '2023-04-01 08:53:23',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 73,
                'name' => 'Project Category Edit',
                'parent' => 'Project Category',
                'status' => 1,
                'updated_at' => '2023-04-01 08:53:23',
            ),
            42 => 
            array (
                'created_at' => '2023-04-01 08:53:23',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 74,
                'name' => 'Project Category Delete',
                'parent' => 'Project Category',
                'status' => 1,
                'updated_at' => '2023-04-01 08:53:23',
            ),
            43 => 
            array (
                'created_at' => '2023-04-01 08:53:23',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 75,
                'name' => 'Project Category View',
                'parent' => 'Project Category',
                'status' => 1,
                'updated_at' => '2023-04-01 08:53:23',
            ),
            44 => 
            array (
                'created_at' => '2023-04-01 08:53:23',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 76,
                'name' => 'Project Category Print',
                'parent' => 'Project Category',
                'status' => 1,
                'updated_at' => '2023-04-01 08:53:23',
            ),
            45 => 
            array (
                'created_at' => '2023-04-01 08:53:23',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 77,
                'name' => 'Project Category Edit_history',
                'parent' => 'Project Category',
                'status' => 1,
                'updated_at' => '2023-04-01 08:53:23',
            ),
            46 => 
            array (
                'created_at' => '2023-04-01 10:15:03',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 91,
                'name' => 'Project Information Edit_history',
                'parent' => 'Project Information',
                'status' => 1,
                'updated_at' => '2023-04-01 10:15:03',
            ),
            47 => 
            array (
                'created_at' => '2023-04-02 05:48:12',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 98,
                'name' => 'Testimonial Edit_history',
                'parent' => 'Testimonial',
                'status' => 1,
                'updated_at' => '2023-04-02 05:48:12',
            ),
            48 => 
            array (
                'created_at' => '2023-04-03 06:46:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 113,
                'name' => 'Our Team Edit_history',
                'parent' => 'Our Team',
                'status' => 1,
                'updated_at' => '2023-04-03 06:46:32',
            ),
            49 => 
            array (
                'created_at' => '2023-04-03 10:39:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 114,
                'name' => 'Menu List',
                'parent' => 'Menu',
                'status' => 1,
                'updated_at' => '2023-04-03 10:39:32',
            ),
            50 => 
            array (
                'created_at' => '2023-04-03 10:39:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 115,
                'name' => 'Menu Create',
                'parent' => 'Menu',
                'status' => 1,
                'updated_at' => '2023-04-03 10:39:32',
            ),
            51 => 
            array (
                'created_at' => '2023-04-03 10:39:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 116,
                'name' => 'Menu Edit',
                'parent' => 'Menu',
                'status' => 1,
                'updated_at' => '2023-04-03 10:39:32',
            ),
            52 => 
            array (
                'created_at' => '2023-04-03 10:39:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 117,
                'name' => 'Menu Delete',
                'parent' => 'Menu',
                'status' => 1,
                'updated_at' => '2023-04-03 10:39:32',
            ),
            53 => 
            array (
                'created_at' => '2023-04-03 10:39:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 118,
                'name' => 'Menu View',
                'parent' => 'Menu',
                'status' => 1,
                'updated_at' => '2023-04-03 10:39:32',
            ),
            54 => 
            array (
                'created_at' => '2023-04-03 10:39:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 119,
                'name' => 'Menu Deleted_list',
                'parent' => 'Menu',
                'status' => 1,
                'updated_at' => '2023-04-03 10:39:32',
            ),
            55 => 
            array (
                'created_at' => '2023-04-03 10:39:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 120,
                'name' => 'Menu Restore',
                'parent' => 'Menu',
                'status' => 1,
                'updated_at' => '2023-04-03 10:39:32',
            ),
            56 => 
            array (
                'created_at' => '2023-04-03 10:39:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 121,
                'name' => 'Menu Permanent_delete',
                'parent' => 'Menu',
                'status' => 1,
                'updated_at' => '2023-04-03 10:39:32',
            ),
            57 => 
            array (
                'created_at' => '2023-04-05 07:01:18',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 128,
                'name' => 'Member Edit_history',
                'parent' => 'Member',
                'status' => 1,
                'updated_at' => '2023-04-05 07:01:18',
            ),
            58 => 
            array (
                'created_at' => '2023-04-05 07:01:18',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 129,
                'name' => 'Member Deleted_list',
                'parent' => 'Member',
                'status' => 1,
                'updated_at' => '2023-04-05 07:01:18',
            ),
            59 => 
            array (
                'created_at' => '2023-04-05 07:01:18',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 131,
                'name' => 'Member Permanent_delete',
                'parent' => 'Member',
                'status' => 1,
                'updated_at' => '2023-04-05 07:01:18',
            ),
            60 => 
            array (
                'created_at' => '2023-06-11 13:35:49',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 132,
                'name' => 'Pages List',
                'parent' => 'Pages',
                'status' => 1,
                'updated_at' => '2023-06-11 13:35:49',
            ),
            61 => 
            array (
                'created_at' => '2023-06-11 13:38:49',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 133,
                'name' => 'Principle List',
                'parent' => 'Principle',
                'status' => 1,
                'updated_at' => '2023-06-11 13:38:49',
            ),
            62 => 
            array (
                'created_at' => '2023-06-11 13:54:53',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 134,
                'name' => 'Photo Gallary List',
                'parent' => 'Photo Gallary',
                'status' => 1,
                'updated_at' => '2023-06-11 13:54:53',
            ),
            63 => 
            array (
                'created_at' => '2023-06-11 13:55:31',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 135,
                'name' => 'Video Gallary List',
                'parent' => 'Video Gallary',
                'status' => 1,
                'updated_at' => '2023-06-11 13:55:31',
            ),
            64 => 
            array (
                'created_at' => '2023-06-11 14:02:50',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 136,
                'name' => 'Notices List',
                'parent' => 'Notices',
                'status' => 1,
                'updated_at' => '2023-06-11 14:02:50',
            ),
            65 => 
            array (
                'created_at' => '2023-06-11 14:09:57',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 137,
                'name' => 'Link List',
                'parent' => 'Link',
                'status' => 1,
                'updated_at' => '2023-06-11 14:09:57',
            ),
            66 => 
            array (
                'created_at' => '2023-06-11 14:28:27',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 138,
                'name' => 'Add Members List',
                'parent' => 'Add Members',
                'status' => 1,
                'updated_at' => '2023-06-11 14:28:27',
            ),
            67 => 
            array (
                'created_at' => '2023-06-13 13:35:34',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 139,
                'name' => 'Academic Calender List',
                'parent' => 'Academic Calender',
                'status' => 1,
                'updated_at' => '2023-06-13 13:35:34',
            ),
            68 => 
            array (
                'created_at' => '2023-06-13 13:36:26',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 140,
                'name' => 'Class Routine List',
                'parent' => 'Class Routine',
                'status' => 1,
                'updated_at' => '2023-06-13 13:36:26',
            ),
            69 => 
            array (
                'created_at' => '2023-06-13 13:38:27',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 141,
                'name' => 'Holiday List List',
                'parent' => 'Holiday List',
                'status' => 1,
                'updated_at' => '2023-06-13 13:38:27',
            ),
            70 => 
            array (
                'created_at' => '2023-06-13 13:41:20',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 142,
                'name' => 'Prospects List',
                'parent' => 'Prospects',
                'status' => 1,
                'updated_at' => '2023-06-13 13:41:20',
            ),
            71 => 
            array (
                'created_at' => '2023-06-13 13:41:54',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 143,
                'name' => 'Admission Rules List',
                'parent' => 'Admission Rules',
                'status' => 1,
                'updated_at' => '2023-06-13 13:41:54',
            ),
            72 => 
            array (
                'created_at' => '2023-06-13 13:42:38',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 144,
                'name' => 'Admission Procedure List',
                'parent' => 'Admission Procedure',
                'status' => 1,
                'updated_at' => '2023-06-13 13:42:38',
            ),
            73 => 
            array (
                'created_at' => '2023-06-13 13:43:41',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 145,
                'name' => 'Admission Result List',
                'parent' => 'Admission Result',
                'status' => 1,
                'updated_at' => '2023-06-13 13:43:41',
            ),
            74 => 
            array (
                'created_at' => '2023-06-13 13:44:26',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 146,
                'name' => 'Exam Question List',
                'parent' => 'Exam Question',
                'status' => 1,
                'updated_at' => '2023-06-13 13:44:26',
            ),
            75 => 
            array (
                'created_at' => '2023-06-13 14:24:49',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 147,
                'name' => 'Admission Info. List',
                'parent' => 'Admission Info.',
                'status' => 1,
                'updated_at' => '2023-06-13 14:24:49',
            ),
            76 => 
            array (
                'created_at' => '2023-06-14 05:55:09',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 148,
                'name' => 'Add Class List',
                'parent' => 'Add Class',
                'status' => 1,
                'updated_at' => '2023-06-14 05:55:09',
            ),
            77 => 
            array (
                'created_at' => '2023-06-14 05:55:42',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 149,
                'name' => 'Add Group List',
                'parent' => 'Add Group',
                'status' => 1,
                'updated_at' => '2023-06-14 05:55:42',
            ),
            78 => 
            array (
                'created_at' => '2023-06-14 05:56:11',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 150,
                'name' => 'Add Section List',
                'parent' => 'Add Section',
                'status' => 1,
                'updated_at' => '2023-06-14 05:56:11',
            ),
            79 => 
            array (
                'created_at' => '2023-06-15 05:54:02',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 151,
                'name' => 'Exam Routine List',
                'parent' => 'Exam Routine',
                'status' => 1,
                'updated_at' => '2023-06-15 05:54:02',
            ),
            80 => 
            array (
                'created_at' => '2023-06-15 05:54:32',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 152,
                'name' => 'Syllabus List',
                'parent' => 'Syllabus',
                'status' => 1,
                'updated_at' => '2023-06-15 05:54:32',
            ),
            81 => 
            array (
                'created_at' => '2023-06-15 05:54:59',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 153,
                'name' => 'Lesson Plan List',
                'parent' => 'Lesson Plan',
                'status' => 1,
                'updated_at' => '2023-06-15 05:54:59',
            ),
            82 => 
            array (
                'created_at' => '2023-06-15 05:55:51',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 154,
                'name' => 'Suggestion List',
                'parent' => 'Suggestion',
                'status' => 1,
                'updated_at' => '2023-06-15 05:55:51',
            ),
            83 => 
            array (
                'created_at' => '2023-06-15 06:31:38',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 155,
                'name' => 'Department List',
                'parent' => 'Department',
                'status' => 1,
                'updated_at' => '2023-06-15 06:31:38',
            ),
            84 => 
            array (
                'created_at' => '2023-06-15 06:32:10',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 156,
                'name' => 'Teacher & Staff List',
                'parent' => 'Teacher & Staff',
                'status' => 1,
                'updated_at' => '2023-06-15 06:32:10',
            ),
            85 => 
            array (
                'created_at' => '2023-06-18 05:29:49',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 157,
                'name' => 'Website Setting',
                'parent' => 'Website Setting',
                'status' => 1,
                'updated_at' => '2023-06-18 05:29:49',
            ),
            86 => 
            array (
                'created_at' => '2023-06-27 09:20:56',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 158,
                'name' => 'View Admission Data List',
                'parent' => 'View Admission Data',
                'status' => 1,
                'updated_at' => '2023-06-27 09:20:56',
            ),
            87 => 
            array (
                'created_at' => '2023-06-27 09:20:56',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 159,
                'name' => 'View Admission Data View',
                'parent' => 'View Admission Data',
                'status' => 1,
                'updated_at' => '2023-06-27 09:20:56',
            ),
            88 => 
            array (
                'created_at' => '2023-07-16 05:09:11',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 160,
                'name' => 'Vice Principal Message List',
                'parent' => 'Vice Principal Message',
                'status' => 1,
                'updated_at' => '2023-07-16 05:09:11',
            ),
            89 => 
            array (
                'created_at' => '2023-07-16 05:09:11',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 161,
                'name' => 'Vice Principal Message Create',
                'parent' => 'Vice Principal Message',
                'status' => 1,
                'updated_at' => '2023-07-16 05:09:11',
            ),
            90 => 
            array (
                'created_at' => '2023-07-16 05:09:11',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 162,
                'name' => 'Vice Principal Message Edit',
                'parent' => 'Vice Principal Message',
                'status' => 1,
                'updated_at' => '2023-07-16 05:09:11',
            ),
            91 => 
            array (
                'created_at' => '2023-07-16 05:09:11',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 163,
                'name' => 'Vice Principal Message Delete',
                'parent' => 'Vice Principal Message',
                'status' => 1,
                'updated_at' => '2023-07-16 05:09:11',
            ),
            92 => 
            array (
                'created_at' => '2023-07-16 05:09:11',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 164,
                'name' => 'Vice Principal Message View',
                'parent' => 'Vice Principal Message',
                'status' => 1,
                'updated_at' => '2023-07-16 05:09:11',
            ),
            93 => 
            array (
                'created_at' => '2023-09-10 09:47:13',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 165,
                'name' => 'Teaching permission and recognition List',
                'parent' => 'Teaching permission and recognition',
                'status' => 1,
                'updated_at' => '2023-09-10 09:47:13',
            ),
            94 => 
            array (
                'created_at' => '2023-09-10 09:47:13',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 166,
                'name' => 'Teaching permission and recognition Create',
                'parent' => 'Teaching permission and recognition',
                'status' => 1,
                'updated_at' => '2023-09-10 09:47:13',
            ),
            95 => 
            array (
                'created_at' => '2023-09-10 09:47:13',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 167,
                'name' => 'Teaching permission and recognition Edit',
                'parent' => 'Teaching permission and recognition',
                'status' => 1,
                'updated_at' => '2023-09-10 09:47:13',
            ),
            96 => 
            array (
                'created_at' => '2023-09-10 09:47:14',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 168,
                'name' => 'Teaching permission and recognition Delete',
                'parent' => 'Teaching permission and recognition',
                'status' => 1,
                'updated_at' => '2023-09-10 09:47:14',
            ),
            97 => 
            array (
                'created_at' => '2023-09-10 09:47:14',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 169,
                'name' => 'Teaching permission and recognition View',
                'parent' => 'Teaching permission and recognition',
                'status' => 1,
                'updated_at' => '2023-09-10 09:47:14',
            ),
            98 => 
            array (
                'created_at' => '2023-09-10 09:47:14',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 170,
                'name' => 'Teaching permission and recognition Print',
                'parent' => 'Teaching permission and recognition',
                'status' => 1,
                'updated_at' => '2023-09-10 09:47:14',
            ),
            99 => 
            array (
                'created_at' => '2023-09-10 09:47:14',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 171,
                'name' => 'Teaching permission and recognition Edit_history',
                'parent' => 'Teaching permission and recognition',
                'status' => 1,
                'updated_at' => '2023-09-10 09:47:14',
            ),
            100 => 
            array (
                'created_at' => '2023-09-10 09:47:14',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 172,
                'name' => 'Teaching permission and recognition Deleted_list',
                'parent' => 'Teaching permission and recognition',
                'status' => 1,
                'updated_at' => '2023-09-10 09:47:14',
            ),
            101 => 
            array (
                'created_at' => '2023-09-10 09:47:14',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 173,
                'name' => 'Teaching permission and recognition Restore',
                'parent' => 'Teaching permission and recognition',
                'status' => 1,
                'updated_at' => '2023-09-10 09:47:14',
            ),
            102 => 
            array (
                'created_at' => '2023-09-10 09:47:14',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 174,
                'name' => 'Teaching permission and recognition Permanent_delete',
                'parent' => 'Teaching permission and recognition',
                'status' => 1,
                'updated_at' => '2023-09-10 09:47:14',
            ),
            103 => 
            array (
                'created_at' => '2023-09-10 09:48:59',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 175,
                'name' => 'MPO_Nationalization Info List',
                'parent' => 'MPO_Nationalization Info',
                'status' => 1,
                'updated_at' => '2023-09-10 09:48:59',
            ),
            104 => 
            array (
                'created_at' => '2023-09-10 09:48:59',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 176,
                'name' => 'MPO_Nationalization Info Create',
                'parent' => 'MPO_Nationalization Info',
                'status' => 1,
                'updated_at' => '2023-09-10 09:48:59',
            ),
            105 => 
            array (
                'created_at' => '2023-09-10 09:48:59',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 177,
                'name' => 'MPO_Nationalization Info Edit',
                'parent' => 'MPO_Nationalization Info',
                'status' => 1,
                'updated_at' => '2023-09-10 09:48:59',
            ),
            106 => 
            array (
                'created_at' => '2023-09-10 09:48:59',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 178,
                'name' => 'MPO_Nationalization Info Delete',
                'parent' => 'MPO_Nationalization Info',
                'status' => 1,
                'updated_at' => '2023-09-10 09:48:59',
            ),
            107 => 
            array (
                'created_at' => '2023-09-10 09:48:59',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 179,
                'name' => 'MPO_Nationalization Info View',
                'parent' => 'MPO_Nationalization Info',
                'status' => 1,
                'updated_at' => '2023-09-10 09:48:59',
            ),
            108 => 
            array (
                'created_at' => '2023-09-10 09:48:59',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 180,
                'name' => 'MPO_Nationalization Info Print',
                'parent' => 'MPO_Nationalization Info',
                'status' => 1,
                'updated_at' => '2023-09-10 09:48:59',
            ),
            109 => 
            array (
                'created_at' => '2023-09-10 09:48:59',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 181,
                'name' => 'MPO_Nationalization Info Edit_history',
                'parent' => 'MPO_Nationalization Info',
                'status' => 1,
                'updated_at' => '2023-09-10 09:48:59',
            ),
            110 => 
            array (
                'created_at' => '2023-09-10 09:48:59',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 182,
                'name' => 'MPO_Nationalization Info Deleted_list',
                'parent' => 'MPO_Nationalization Info',
                'status' => 1,
                'updated_at' => '2023-09-10 09:48:59',
            ),
            111 => 
            array (
                'created_at' => '2023-09-10 09:48:59',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 183,
                'name' => 'MPO_Nationalization Info Restore',
                'parent' => 'MPO_Nationalization Info',
                'status' => 1,
                'updated_at' => '2023-09-10 09:48:59',
            ),
            112 => 
            array (
                'created_at' => '2023-09-10 09:48:59',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 184,
                'name' => 'MPO_Nationalization Info Permanent_delete',
                'parent' => 'MPO_Nationalization Info',
                'status' => 1,
                'updated_at' => '2023-09-10 09:48:59',
            ),
            113 => 
            array (
                'created_at' => '2023-09-12 06:41:24',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 185,
                'name' => 'Student Attendance Information List',
                'parent' => 'Student Attendance Information',
                'status' => 1,
                'updated_at' => '2023-09-12 06:41:24',
            ),
            114 => 
            array (
                'created_at' => '2023-09-12 06:41:24',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 186,
                'name' => 'Student Attendance Information Create',
                'parent' => 'Student Attendance Information',
                'status' => 1,
                'updated_at' => '2023-09-12 06:41:24',
            ),
            115 => 
            array (
                'created_at' => '2023-09-12 06:41:24',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 187,
                'name' => 'Student Attendance Information Edit',
                'parent' => 'Student Attendance Information',
                'status' => 1,
                'updated_at' => '2023-09-12 06:41:24',
            ),
            116 => 
            array (
                'created_at' => '2023-09-12 06:41:24',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 188,
                'name' => 'Student Attendance Information Delete',
                'parent' => 'Student Attendance Information',
                'status' => 1,
                'updated_at' => '2023-09-12 06:41:24',
            ),
            117 => 
            array (
                'created_at' => '2023-09-12 06:41:24',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 189,
                'name' => 'Student Attendance Information View',
                'parent' => 'Student Attendance Information',
                'status' => 1,
                'updated_at' => '2023-09-12 06:41:24',
            ),
            118 => 
            array (
                'created_at' => '2023-09-12 06:41:24',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 190,
                'name' => 'Student Attendance Information Print',
                'parent' => 'Student Attendance Information',
                'status' => 1,
                'updated_at' => '2023-09-12 06:41:24',
            ),
            119 => 
            array (
                'created_at' => '2023-09-12 06:41:24',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 191,
                'name' => 'Student Attendance Information Edit_history',
                'parent' => 'Student Attendance Information',
                'status' => 1,
                'updated_at' => '2023-09-12 06:41:24',
            ),
            120 => 
            array (
                'created_at' => '2023-09-12 06:41:24',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 192,
                'name' => 'Student Attendance Information Deleted_list',
                'parent' => 'Student Attendance Information',
                'status' => 1,
                'updated_at' => '2023-09-12 06:41:24',
            ),
            121 => 
            array (
                'created_at' => '2023-09-12 06:41:24',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 193,
                'name' => 'Student Attendance Information Restore',
                'parent' => 'Student Attendance Information',
                'status' => 1,
                'updated_at' => '2023-09-12 06:41:24',
            ),
            122 => 
            array (
                'created_at' => '2023-09-12 06:41:24',
                'deleted_at' => NULL,
                'guard_name' => 'web',
                'id' => 194,
                'name' => 'Student Attendance Information Permanent_delete',
                'parent' => 'Student Attendance Information',
                'status' => 1,
                'updated_at' => '2023-09-12 06:41:24',
            ),
        ));
        
        
    }
}