<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SubjectInfosTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('subject_infos')->delete();
        
        \DB::table('subject_infos')->insert(array (
            0 => 
            array (
                'id' => 1,
                'class_id' => 2,
                'group_id' => 4,
                'subject_name' => 'Bangla',
                'subject_code' => '101-102',
                'select_subject_type' => 'CompulsorySubject',
                'serial' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'class_id' => 2,
                'group_id' => 5,
                'subject_name' => 'Bangla',
                'subject_code' => '101-102',
                'select_subject_type' => 'CompulsorySubject',
                'serial' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'class_id' => 2,
                'group_id' => 6,
                'subject_name' => 'Bangla',
                'subject_code' => '101-102',
                'select_subject_type' => 'CompulsorySubject',
                'serial' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'class_id' => 2,
                'group_id' => 4,
                'subject_name' => 'English',
                'subject_code' => '107-108',
                'select_subject_type' => 'CompulsorySubject',
                'serial' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'class_id' => 2,
                'group_id' => 5,
                'subject_name' => 'English',
                'subject_code' => '107-108',
                'select_subject_type' => 'CompulsorySubject',
                'serial' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'class_id' => 2,
                'group_id' => 6,
                'subject_name' => 'English',
                'subject_code' => '107-108',
                'select_subject_type' => 'CompulsorySubject',
                'serial' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'class_id' => 2,
                'group_id' => 4,
                'subject_name' => 'ICT',
                'subject_code' => '275',
                'select_subject_type' => 'CompulsorySubject',
                'serial' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'class_id' => 2,
                'group_id' => 5,
                'subject_name' => 'ICT',
                'subject_code' => '275',
                'select_subject_type' => 'CompulsorySubject',
                'serial' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'class_id' => 2,
                'group_id' => 6,
                'subject_name' => 'ICT',
                'subject_code' => '275',
                'select_subject_type' => 'CompulsorySubject',
                'serial' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'class_id' => 2,
                'group_id' => 4,
                'subject_name' => 'Accounting',
                'subject_code' => '253-254',
                'select_subject_type' => 'GroupSubject',
                'serial' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'class_id' => 2,
                'group_id' => 4,
                'subject_name' => 'Finance Banking and Insurance',
                'subject_code' => '292-293',
                'select_subject_type' => 'GroupSubject',
                'serial' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'class_id' => 2,
                'group_id' => 4,
                'subject_name' => 'Economics',
                'subject_code' => '109-110',
                'select_subject_type' => 'OptionalSubject',
                'serial' => 6,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'class_id' => 2,
                'group_id' => 4,
                'subject_name' => 'Statistcs',
                'subject_code' => '129-130',
                'select_subject_type' => 'OptionalSubject',
                'serial' => 7,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'class_id' => 2,
                'group_id' => 5,
                'subject_name' => 'History',
                'subject_code' => '304-305',
                'select_subject_type' => 'GroupSubject',
                'serial' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'class_id' => 2,
                'group_id' => 5,
                'subject_name' => 'History',
                'subject_code' => '304-305',
                'select_subject_type' => 'OptionalSubject',
                'serial' => 9,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'class_id' => 2,
                'group_id' => 5,
                'subject_name' => 'Islamic History',
                'subject_code' => '267-268',
                'select_subject_type' => 'GroupSubject',
                'serial' => 10,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'class_id' => 2,
                'group_id' => 5,
                'subject_name' => 'Islamic History',
                'subject_code' => '267-268',
                'select_subject_type' => 'OptionalSubject',
                'serial' => 11,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'class_id' => 2,
                'group_id' => 5,
                'subject_name' => 'Civics and good governance',
                'subject_code' => '269-270',
                'select_subject_type' => 'GroupSubject',
                'serial' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'class_id' => 2,
                'group_id' => 5,
                'subject_name' => 'Civics and good governance',
                'subject_code' => '269-270',
                'select_subject_type' => 'OptionalSubject',
                'serial' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'class_id' => 2,
                'group_id' => 5,
                'subject_name' => 'Economics',
                'subject_code' => '109-110',
                'select_subject_type' => 'GroupSubject',
                'serial' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'class_id' => 2,
                'group_id' => 5,
                'subject_name' => 'Economics',
                'subject_code' => '109-110',
                'select_subject_type' => 'OptionalSubject',
                'serial' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'class_id' => 2,
                'group_id' => 5,
                'subject_name' => 'Social Work',
                'subject_code' => '271-272',
                'select_subject_type' => 'GroupSubject',
                'serial' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'class_id' => 2,
                'group_id' => 5,
                'subject_name' => 'Social Work',
                'subject_code' => '271-272',
                'select_subject_type' => 'OptionalSubject',
                'serial' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'class_id' => 2,
                'group_id' => 5,
                'subject_name' => 'Logic',
                'subject_code' => '121-122',
                'select_subject_type' => 'GroupSubject',
                'serial' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'class_id' => 2,
                'group_id' => 5,
                'subject_name' => 'Logic',
                'subject_code' => '121-122',
                'select_subject_type' => 'OptionalSubject',
                'serial' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'class_id' => 2,
                'group_id' => 4,
                'subject_name' => 'Business Organization and Management',
                'subject_code' => '277-278',
                'select_subject_type' => 'GroupSubject',
                'serial' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'class_id' => 2,
                'group_id' => 6,
                'subject_name' => 'Physics',
                'subject_code' => '174-175',
                'select_subject_type' => 'GroupSubject',
                'serial' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'class_id' => 2,
                'group_id' => 6,
                'subject_name' => 'Chemistry',
                'subject_code' => '176-177',
                'select_subject_type' => 'GroupSubject',
                'serial' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'class_id' => 2,
                'group_id' => 6,
                'subject_name' => 'Higher Mathematics',
                'subject_code' => '265-266',
                'select_subject_type' => 'GroupSubject',
                'serial' => 7,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'class_id' => 2,
                'group_id' => 6,
                'subject_name' => 'Higher Mathematics',
                'subject_code' => '265-266',
                'select_subject_type' => 'OptionalSubject',
                'serial' => 9,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'class_id' => 2,
                'group_id' => 6,
                'subject_name' => 'BIology',
                'subject_code' => '178-179',
                'select_subject_type' => 'GroupSubject',
                'serial' => 6,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'class_id' => 2,
                'group_id' => 6,
                'subject_name' => 'BIology',
                'subject_code' => '178-179',
                'select_subject_type' => 'OptionalSubject',
                'serial' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'class_id' => 1,
                'group_id' => 3,
                'subject_name' => 'BANGLA',
                'subject_code' => '101-102',
                'select_subject_type' => 'CompulsorySubject',
                'serial' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'class_id' => 1,
                'group_id' => 1,
                'subject_name' => 'BANGLA',
                'subject_code' => '101-102',
                'select_subject_type' => 'CompulsorySubject',
                'serial' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'class_id' => 1,
                'group_id' => 2,
                'subject_name' => 'BANGLA',
                'subject_code' => '101-102',
                'select_subject_type' => 'CompulsorySubject',
                'serial' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'class_id' => 1,
                'group_id' => 1,
                'subject_name' => 'ENGLISH',
                'subject_code' => '107-108',
                'select_subject_type' => 'CompulsorySubject',
                'serial' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'class_id' => 1,
                'group_id' => 2,
                'subject_name' => 'ENGLISH',
                'subject_code' => '107-108',
                'select_subject_type' => 'CompulsorySubject',
                'serial' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'class_id' => 1,
                'group_id' => 3,
                'subject_name' => 'ENGLISH',
                'subject_code' => '107-108',
                'select_subject_type' => 'CompulsorySubject',
                'serial' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'class_id' => 1,
                'group_id' => 3,
                'subject_name' => 'ICT',
                'subject_code' => '275',
                'select_subject_type' => 'CompulsorySubject',
                'serial' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'class_id' => 1,
                'group_id' => 3,
                'subject_name' => 'PHYSICS',
                'subject_code' => '174-175',
                'select_subject_type' => 'GroupSubject',
                'serial' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'class_id' => 1,
                'group_id' => 3,
                'subject_name' => 'CHEMISTRY',
                'subject_code' => '176-177',
                'select_subject_type' => 'GroupSubject',
                'serial' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'class_id' => 1,
                'group_id' => 3,
                'subject_name' => 'BIOLOGY',
                'subject_code' => '178-179',
                'select_subject_type' => 'GroupSubject',
                'serial' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'class_id' => 1,
                'group_id' => 3,
                'subject_name' => 'HIGHER MATH',
                'subject_code' => '265-266',
                'select_subject_type' => 'GroupSubject',
                'serial' => 7,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'class_id' => 1,
                'group_id' => 3,
                'subject_name' => 'HIGHER MATH',
                'subject_code' => '265-266',
                'select_subject_type' => 'OptionalSubject',
                'serial' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'class_id' => 1,
                'group_id' => 3,
                'subject_name' => 'BIOLOGY',
                'subject_code' => '178-179',
                'select_subject_type' => 'OptionalSubject',
                'serial' => 9,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'class_id' => 1,
                'group_id' => 1,
                'subject_name' => 'ACCOUNTING',
                'subject_code' => '253-254',
                'select_subject_type' => 'GroupSubject',
                'serial' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'class_id' => 1,
                'group_id' => 1,
                'subject_name' => 'ICT',
                'subject_code' => '275',
                'select_subject_type' => 'CompulsorySubject',
                'serial' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'class_id' => 1,
                'group_id' => 1,
                'subject_name' => 'Finance Banking and Insurance',
                'subject_code' => '292-293',
                'select_subject_type' => 'GroupSubject',
                'serial' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'class_id' => 1,
                'group_id' => 1,
                'subject_name' => 'Business Organization and Management',
                'subject_code' => '277-278',
                'select_subject_type' => 'GroupSubject',
                'serial' => 6,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'class_id' => 1,
                'group_id' => 1,
                'subject_name' => 'Economics',
                'subject_code' => '109-110',
                'select_subject_type' => 'OptionalSubject',
                'serial' => 7,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'class_id' => 1,
                'group_id' => 2,
                'subject_name' => 'ICT',
                'subject_code' => '275',
                'select_subject_type' => 'CompulsorySubject',
                'serial' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'class_id' => 1,
                'group_id' => 2,
                'subject_name' => 'Social Work',
                'subject_code' => '271-272',
                'select_subject_type' => 'GroupSubject',
                'serial' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'class_id' => 1,
                'group_id' => 2,
                'subject_name' => 'Social Work',
                'subject_code' => '271-272',
                'select_subject_type' => 'OptionalSubject',
                'serial' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'class_id' => 1,
                'group_id' => 1,
                'subject_name' => 'Statistcs',
                'subject_code' => '129-130',
                'select_subject_type' => 'OptionalSubject',
                'serial' => 7,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'class_id' => 1,
                'group_id' => 2,
                'subject_name' => 'Civics and good governance',
                'subject_code' => '269-270',
                'select_subject_type' => 'GroupSubject',
                'serial' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'class_id' => 1,
                'group_id' => 2,
                'subject_name' => 'Civics and good governance',
                'subject_code' => '269-270',
                'select_subject_type' => 'OptionalSubject',
                'serial' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'class_id' => 1,
                'group_id' => 2,
                'subject_name' => 'Islamic History',
                'subject_code' => '267-268',
                'select_subject_type' => 'GroupSubject',
                'serial' => 7,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'class_id' => 1,
                'group_id' => 2,
                'subject_name' => 'Islamic History',
                'subject_code' => '267-268',
                'select_subject_type' => 'OptionalSubject',
                'serial' => 7,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'class_id' => 1,
                'group_id' => 2,
                'subject_name' => 'History',
                'subject_code' => '304-305',
                'select_subject_type' => 'GroupSubject',
                'serial' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'class_id' => 1,
                'group_id' => 2,
                'subject_name' => 'History',
                'subject_code' => '304-305',
                'select_subject_type' => 'OptionalSubject',
                'serial' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'class_id' => 1,
                'group_id' => 2,
                'subject_name' => 'Logic',
                'subject_code' => '121-122',
                'select_subject_type' => 'GroupSubject',
                'serial' => 9,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'class_id' => 1,
                'group_id' => 2,
                'subject_name' => 'Logic',
                'subject_code' => '121-122',
                'select_subject_type' => 'OptionalSubject',
                'serial' => 9,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'class_id' => 1,
                'group_id' => 2,
                'subject_name' => 'Economics',
                'subject_code' => '109-110',
                'select_subject_type' => 'GroupSubject',
                'serial' => 10,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'class_id' => 1,
                'group_id' => 2,
                'subject_name' => 'Economics',
                'subject_code' => '109-110',
                'select_subject_type' => 'OptionalSubject',
                'serial' => 10,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}