<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TeacherstaffTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('teacherstaff')->delete();
        
        \DB::table('teacherstaff')->insert(array (
            0 => 
            array (
                'blood' => NULL,
                'created_at' => NULL,
                'department_id' => 27,
                'designation' => 'সহকারী অধ্যাপক, হিসাব বিজ্ঞান বিভাগ',
                'dob' => NULL,
            'education' => '<p><span style="color: rgb(51, 51, 51); font-family: Roboto, sans-serif;">বি কম(সম্মন), এস , কম(হিসাববিজ্ঞান)</span><br></p>',
                'email' => 'riadbhuiyan@gmail.com',
                'father_name' => NULL,
                'gender' => 'Male',
                'id' => 105,
                'image' => 'teacherstaff_image/6849.png',
                'join_date' => NULL,
                'mobile' => '01911893814',
                'mother_name' => NULL,
                'mpo_date' => NULL,
                'name' => 'হাছান মাহমুদ রিয়াদ ভূঁঞা',
                'nid' => NULL,
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Married',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'blood' => NULL,
                'created_at' => NULL,
                'department_id' => 27,
                'designation' => 'লেকচারার',
                'dob' => NULL,
            'education' => '<p>S.S.C -1st Class,H.S.C-1st Class,B.B.A- 3.31(4),M.B.A-3.44(4)<br></p>',
                'email' => 'washimaisdu@gmail.com',
                'father_name' => NULL,
                'gender' => 'Male',
                'id' => 106,
                'image' => 'teacherstaff_image/2251.jpg',
                'join_date' => NULL,
                'mobile' => '01710681360',
                'mother_name' => NULL,
                'mpo_date' => NULL,
                'name' => 'মো. ওয়াসিম পাটোয়ারী',
                'nid' => NULL,
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Unmarried',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'blood' => 'null',
                'created_at' => NULL,
                'department_id' => 28,
                'designation' => 'অধ্যাপক',
                'dob' => NULL,
            'education' => '<p><span style="color: rgb(51, 51, 51); font-family: Roboto, sans-serif;">এস.এস.সি - ১ম বিভাগ, এইচ.এস.সি- ১ম বিভাগ,স্নাতক (সম্মন)-২য় শ্রেণী,স্নাতকোত্তর - ২য় শ্রেণী</span><br></p>',
                'email' => 'humayunk990@gmail.com',
                'father_name' => 'মো : ফজলের রহমান',
                'gender' => 'Male',
                'id' => 107,
                'image' => 'teacherstaff_image/2231.jpg',
                'join_date' => NULL,
                'mobile' => '01715005269',
                'mother_name' => 'সায়েরা বেগম',
                'mpo_date' => NULL,
                'name' => 'মো : হুমায়ুন কবীর',
                'nid' => 'null',
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Married',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'blood' => NULL,
                'created_at' => NULL,
                'department_id' => 28,
            'designation' => 'সহযোগী অধ্যাপক(বাংলা)',
                'dob' => NULL,
            'education' => '<p><span style="color: rgb(51, 51, 51); font-family: Roboto, sans-serif;">বি এ (অনার্স), এম এ (বাংলা)</span><br></p>',
                'email' => 'rejamahmuda75@gmail.com',
                'father_name' => NULL,
                'gender' => 'Male',
                'id' => 108,
                'image' => 'teacherstaff_image/7658.jpg',
                'join_date' => NULL,
                'mobile' => '01818214080',
                'mother_name' => NULL,
                'mpo_date' => NULL,
                'name' => 'কাজী মোহাম্মদ রেজাউল হক',
                'nid' => NULL,
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Married',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'blood' => NULL,
                'created_at' => NULL,
                'department_id' => 27,
            'designation' => 'অধ্যক্ষ (ভারপ্রাপ্ত)',
                'dob' => NULL,
                'education' => '<p>MBA<br></p>',
                'email' => 'info@fgc.gov.bd',
                'father_name' => NULL,
                'gender' => 'Male',
                'id' => 109,
                'image' => 'teacherstaff_image/7407.jpg',
                'join_date' => NULL,
                'mobile' => '01911893814',
                'mother_name' => NULL,
                'mpo_date' => NULL,
                'name' => 'প্রফেসর মোহাম্মদ দেলোয়ার হোসেন',
                'nid' => NULL,
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Married',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'blood' => NULL,
                'created_at' => NULL,
                'department_id' => 43,
                'designation' => 'সহযোগী অধ্যাপক উদ্ভিদবিদ্যা বিভাগ',
                'dob' => NULL,
            'education' => '<p><span style="color: rgb(51, 51, 51); font-family: Roboto, sans-serif;">এস.এস.সি(১ম বিভাগ) ,এইচ.এস.সি(১ম বিভাগ) ,বি.এস.সি(অনার্স) ,এম.এস.সি(১ম শ্রেণী)</span><br></p>',
                'email' => 'harun.rashid.56th@gmail.com',
                'father_name' => NULL,
                'gender' => 'Male',
                'id' => 110,
                'image' => 'teacherstaff_image/7031.jpg',
                'join_date' => NULL,
                'mobile' => '01554332209',
                'mother_name' => NULL,
                'mpo_date' => NULL,
                'name' => 'হারুনুর রশীদ',
                'nid' => NULL,
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Married',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'blood' => NULL,
                'created_at' => NULL,
                'department_id' => 43,
                'designation' => 'সহকারী অধ্যাপক',
                'dob' => NULL,
                'education' => '<p>null</p>',
                'email' => 'mosarof34@gmail.com',
                'father_name' => NULL,
                'gender' => 'Male',
                'id' => 111,
                'image' => 'teacherstaff_image/8277.jpg',
                'join_date' => NULL,
                'mobile' => '01716086534',
                'mother_name' => NULL,
                'mpo_date' => NULL,
                'name' => 'মোঃমোশারফ হোসেন',
                'nid' => NULL,
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Married',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'blood' => 'null',
                'created_at' => NULL,
                'department_id' => 43,
                'designation' => 'প্রভাষক',
                'dob' => NULL,
                'education' => '<p>Null</p>',
                'email' => 'ahomodali49@gmail.com',
                'father_name' => 'NULL',
                'gender' => 'Male',
                'id' => 112,
                'image' => 'teacherstaff_image/3632.jpg',
                'join_date' => NULL,
                'mobile' => '01715954749',
                'mother_name' => 'NULL',
                'mpo_date' => NULL,
                'name' => 'আহমদ আলী',
                'nid' => 'null',
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Unmarried',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'blood' => NULL,
                'created_at' => NULL,
                'department_id' => 43,
                'designation' => 'সহকারী অধ্যাপক,উদ্ভিদ বিদ্যা বিভাগ',
                'dob' => NULL,
            'education' => '<p><span style="color: rgb(51, 51, 51); font-family: Roboto, sans-serif;">বি. এস সি(সম্মান)প্রথম শ্রেণী এম এস সি (উদ্ভিদ বিদ্যা)প্রথম শ্রেণী</span><br></p>',
                'email' => 'shanawzfeni1987@gmail.com',
                'father_name' => NULL,
                'gender' => 'Male',
                'id' => 113,
                'image' => 'teacherstaff_image/5520.jpg',
                'join_date' => NULL,
                'mobile' => '01673463639',
                'mother_name' => NULL,
                'mpo_date' => NULL,
                'name' => 'মোঃশাহনে ওয়াজ ভূঁঞা',
                'nid' => NULL,
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Married',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'blood' => NULL,
                'created_at' => NULL,
                'department_id' => 29,
                'designation' => 'অধ্যাপক',
                'dob' => NULL,
                'education' => '<p>Null</p>',
                'email' => 'dhnes37@gmail.com',
                'father_name' => NULL,
                'gender' => 'Male',
                'id' => 114,
                'image' => 'teacherstaff_image/7394.jpg',
                'join_date' => NULL,
                'mobile' => '01715338737',
                'mother_name' => NULL,
                'mpo_date' => NULL,
                'name' => 'দীনেশ চন্দ্র পাল',
                'nid' => NULL,
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Married',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'blood' => NULL,
                'created_at' => NULL,
                'department_id' => 29,
                'designation' => 'সহযোগী অধ্যাপক',
                'dob' => NULL,
                'education' => '<p>Null</p>',
                'email' => 'nurulajim36@gmail.com',
                'father_name' => NULL,
                'gender' => 'Male',
                'id' => 115,
                'image' => 'teacherstaff_image/9514.jpg',
                'join_date' => NULL,
                'mobile' => '01711395736',
                'mother_name' => NULL,
                'mpo_date' => NULL,
                'name' => 'মোঃ নূরুল আজিম ভূঁইয়া',
                'nid' => NULL,
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Married',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'blood' => 'null',
                'created_at' => NULL,
                'department_id' => 29,
                'designation' => 'প্রভাষক',
                'dob' => NULL,
                'education' => '<p>Null</p>',
                'email' => 'taslima40@gmail.com',
                'father_name' => 'NULL',
                'gender' => 'Female',
                'id' => 116,
                'image' => 'teacherstaff_image/1246.png',
                'join_date' => NULL,
                'mobile' => '01716502640',
                'mother_name' => 'NULL',
                'mpo_date' => NULL,
                'name' => 'তাছলিমা আক্তার',
                'nid' => 'null',
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Married',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'blood' => 'null',
                'created_at' => NULL,
                'department_id' => 39,
                'designation' => 'সহযোগী অধ্যাপক অর্থনীতি বিভাগ',
                'dob' => NULL,
                'education' => '<p>Null<br></p>',
                'email' => 'ayub@gmail.com',
                'father_name' => 'মৃত হাজী নূরুল ইসলাম',
                'gender' => 'Male',
                'id' => 117,
                'image' => 'teacherstaff_image/6711.jpg',
                'join_date' => NULL,
                'mobile' => '01712618147',
                'mother_name' => 'ফিরোজা বেগম',
                'mpo_date' => NULL,
                'name' => 'মো: আইউব',
                'nid' => 'null',
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Married',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'blood' => 'null',
                'created_at' => NULL,
                'department_id' => 39,
                'designation' => 'প্রভাষক, অর্থনীতি বিভাগ',
                'dob' => NULL,
                'education' => '<p>Null</p>',
                'email' => 'zaforbd@yahoo.com',
                'father_name' => 'আবু তাহের',
                'gender' => 'Male',
                'id' => 118,
                'image' => 'teacherstaff_image/3541.jpg',
                'join_date' => NULL,
                'mobile' => '01712571632',
                'mother_name' => 'রেজিয়া বেগম',
                'mpo_date' => NULL,
                'name' => 'আবুজাফর',
                'nid' => 'null',
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Married',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'blood' => NULL,
                'created_at' => NULL,
                'department_id' => 39,
                'designation' => 'সহকারী অধ্যাপক,অধ্যাপক, অর্থনীতি বিভাগ',
                'dob' => NULL,
                'education' => '<p>Null</p>',
                'email' => 'Afrozabanu@gmail.com',
                'father_name' => 'মরহুম এ,কে ,এম ফজলুল হক',
                'gender' => 'Female',
                'id' => 119,
                'image' => 'teacherstaff_image/8517.jpg',
                'join_date' => NULL,
                'mobile' => '01711389748',
                'mother_name' => 'হাসিনা আক্তার',
                'mpo_date' => NULL,
                'name' => 'আফরোজা বানু',
                'nid' => 'null',
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Unmarried',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'blood' => NULL,
                'created_at' => NULL,
                'department_id' => 30,
                'designation' => 'সহকারী প্রফেসর',
                'dob' => NULL,
            'education' => '<table style="border-spacing: 0px; color: rgb(51, 51, 51); font-family: Roboto, sans-serif;"><tbody><tr><td style="padding: 0px;"><p style="margin-bottom: 10px;">নং</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">পরীক্ষার নাম</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">গ্রুপ/বিষয়</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">বোর্ড/বিশ্ববিদ্যালয়</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">বিভাগ/গ্রেড</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;"></p><div>প্রাপ্ত নম্বর/<p style="margin-bottom: 10px;"></p><p style="margin-bottom: 10px;">সিজিপিএ</p></div></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">পরীক্ষার বছর</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">পরীক্ষার তারিখ</p></td></tr><tr><td style="padding: 0px;"><p style="margin-bottom: 10px;">1</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">এস এস সি</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">বিজ্ঞান</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">কুমিল্লা শিক্ষা বোর্ড</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">বি এস এস সি</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">3.88</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">2001</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">2001</p></td></tr><tr><td style="padding: 0px;"><p style="margin-bottom: 10px;">2</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">এইচ এস সি</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">মানবিক</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">চট্রগ্রাম শিক্ষা বোর্ড</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">বি এইচ এস সি</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">3.30</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">2003</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">2003</p></td></tr><tr><td style="padding: 0px;"><p style="margin-bottom: 10px;">3</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">বি এ (সম্মান)</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">ইংরেজী</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">ঢাকা বিশ্ববিদ্যালয়</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">২য় শ্রেণি</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">900</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">2007</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">2009</p></td></tr><tr><td style="padding: 0px;"><p style="margin-bottom: 10px;">4</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">এম এ</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">ইংরেজী</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">ঢাকা বিশ্ববিদ্যালয়</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">২য় শ্রেণি</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">235</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">2008</p></td><td style="padding: 0px;"><p style="margin-bottom: 10px;">2010</p></td></tr></tbody></table>',
                'email' => 'sohelmostaq@gmail.com',
                'father_name' => NULL,
                'gender' => 'Male',
                'id' => 121,
                'image' => 'teacherstaff_image/5995.jpg',
                'join_date' => NULL,
                'mobile' => '01919967374',
                'mother_name' => NULL,
                'mpo_date' => NULL,
                'name' => 'মো. মোস্তাক হোসাইন',
                'nid' => NULL,
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Unmarried',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'blood' => NULL,
                'created_at' => NULL,
                'department_id' => 31,
                'designation' => 'অধ্যাপক',
                'dob' => NULL,
                'education' => '<p>Null</p>',
                'email' => 'fozlealahi04@gmail.com',
                'father_name' => NULL,
                'gender' => 'Male',
                'id' => 122,
                'image' => 'teacherstaff_image/9404.jpg',
                'join_date' => NULL,
                'mobile' => '01911031704',
                'mother_name' => NULL,
                'mpo_date' => NULL,
                'name' => 'মোঃফজলে এলাহী Designation	Mobile No',
                'nid' => NULL,
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Married',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'blood' => NULL,
                'created_at' => NULL,
                'department_id' => 31,
                'designation' => 'সহযোগী অধ্যাপক, ইতিহাস বিভাগ',
                'dob' => NULL,
                'education' => '<p>Null</p>',
                'email' => 'jesmin.chatkil@gmail.com',
                'father_name' => NULL,
                'gender' => 'Female',
                'id' => 123,
                'image' => 'teacherstaff_image/3333.jpg',
                'join_date' => NULL,
                'mobile' => '01717296076',
                'mother_name' => NULL,
                'mpo_date' => NULL,
                'name' => 'মোসাম্মৎ জেসমিন আক্তার',
                'nid' => NULL,
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Married',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'blood' => 'null',
                'created_at' => NULL,
                'department_id' => 31,
                'designation' => 'সহকারী অধ্যাপক',
                'dob' => NULL,
                'education' => '<p>Null</p>',
                'email' => 'harunorrosid09@gmail.com',
                'father_name' => 'NULL',
                'gender' => 'Male',
                'id' => 124,
                'image' => 'teacherstaff_image/5486.jpg',
                'join_date' => NULL,
                'mobile' => '01811253709',
                'mother_name' => 'NULL',
                'mpo_date' => NULL,
                'name' => 'মোহাম্মদ হারুন অর রশিদ',
                'nid' => 'null',
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Married',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'blood' => NULL,
                'created_at' => NULL,
                'department_id' => 32,
                'designation' => 'সহকারী প্রফেসর',
                'dob' => NULL,
            'education' => '<p><span style="color: rgb(51, 51, 51); font-family: Roboto, sans-serif;">HONOURS MASTERS (ISLAMIC HISTORY &amp; CULTURER</span><br></p>',
                'email' => 'zainalabedin93@yahoo.com',
                'father_name' => NULL,
                'gender' => 'Male',
                'id' => 125,
                'image' => 'teacherstaff_image/8428.jpg',
                'join_date' => NULL,
                'mobile' => '01818231520',
                'mother_name' => NULL,
                'mpo_date' => NULL,
                'name' => 'জয়নাল আবেদীন',
                'nid' => NULL,
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Unmarried',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'blood' => NULL,
                'created_at' => NULL,
                'department_id' => 41,
                'designation' => 'সহকারী অধ্যাপক',
                'dob' => NULL,
                'education' => '<p>Null</p>',
                'email' => 'johir076@yahoo.com',
                'father_name' => NULL,
                'gender' => 'Male',
                'id' => 126,
                'image' => 'teacherstaff_image/9151.jpg',
                'join_date' => NULL,
                'mobile' => '01717308799',
                'mother_name' => NULL,
                'mpo_date' => NULL,
                'name' => 'মো : জহির উদ্দিন',
                'nid' => NULL,
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Married',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'blood' => NULL,
                'created_at' => NULL,
                'department_id' => 41,
                'designation' => 'প্রভাষক',
                'dob' => NULL,
                'education' => 'Null',
                'email' => 'litonchodr35@gmail.com',
                'father_name' => NULL,
                'gender' => 'Male',
                'id' => 127,
                'image' => 'teacherstaff_image/3751.jpg',
                'join_date' => NULL,
                'mobile' => '01815342935',
                'mother_name' => NULL,
                'mpo_date' => NULL,
                'name' => 'লিটন চন্দ্র পাল',
                'nid' => NULL,
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Married',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'blood' => NULL,
                'created_at' => NULL,
                'department_id' => 41,
                'designation' => 'লেকচারার',
                'dob' => NULL,
            'education' => '<p><span style="color: rgb(51, 51, 51); font-family: Roboto, sans-serif;">MSc (Mathematics)</span><br></p>',
                'email' => 'didoanulkabir@gmail.com',
                'father_name' => NULL,
                'gender' => 'Male',
                'id' => 128,
                'image' => 'teacherstaff_image/3897.jpg',
                'join_date' => NULL,
                'mobile' => '01719651961',
                'mother_name' => NULL,
                'mpo_date' => NULL,
                'name' => 'MD. DIDOANUL KABIR',
                'nid' => NULL,
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Unmarried',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'blood' => NULL,
                'created_at' => NULL,
                'department_id' => 34,
                'designation' => 'অধ্যাপক',
                'dob' => NULL,
                'education' => '<p>Null</p>',
                'email' => 'likotali81@gmail.com',
                'father_name' => NULL,
                'gender' => 'Male',
                'id' => 129,
                'image' => 'teacherstaff_image/9859.jpg',
                'join_date' => NULL,
                'mobile' => '01711701381',
                'mother_name' => NULL,
                'mpo_date' => NULL,
                'name' => 'মোঃলিয়াকত আলী',
                'nid' => NULL,
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Married',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'blood' => 'null',
                'created_at' => NULL,
                'department_id' => 34,
                'designation' => 'প্রভাষক',
                'dob' => NULL,
                'education' => '<p>Null</p>',
                'email' => 'lutfornahar50@gmail.com',
                'father_name' => 'NULL',
                'gender' => 'Female',
                'id' => 130,
                'image' => 'teacherstaff_image/6684.png',
                'join_date' => NULL,
                'mobile' => '01720283950',
                'mother_name' => 'NULL',
                'mpo_date' => NULL,
                'name' => 'লুৎফুন নাহার',
                'nid' => 'null',
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Married',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'blood' => NULL,
                'created_at' => NULL,
                'department_id' => 35,
                'designation' => 'অধ্যাপক',
                'dob' => NULL,
                'education' => '<p>Null</p>',
                'email' => 'dholonkisnow00@gmail.com',
                'father_name' => NULL,
                'gender' => 'Male',
                'id' => 131,
                'image' => 'teacherstaff_image/4642.jpg',
                'join_date' => NULL,
                'mobile' => '01715599500',
                'mother_name' => NULL,
                'mpo_date' => NULL,
                'name' => 'দোলন কৃষ্ণ সাহা',
                'nid' => NULL,
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Married',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'blood' => NULL,
                'created_at' => NULL,
                'department_id' => 35,
                'designation' => 'সহকারী অধ্যাপক',
                'dob' => NULL,
                'education' => '<p>Null</p>',
                'email' => 'mothhior05@gmail.com',
                'father_name' => NULL,
                'gender' => 'Male',
                'id' => 132,
                'image' => 'teacherstaff_image/3158.jpg',
                'join_date' => NULL,
                'mobile' => '01716397005',
                'mother_name' => NULL,
                'mpo_date' => NULL,
                'name' => 'মোঃমতিউর রহমান',
                'nid' => NULL,
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Married',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'blood' => 'null',
                'created_at' => NULL,
                'department_id' => 35,
                'designation' => 'প্রভাষক,পদার্থ বিজ্ঞান বিভাগ',
                'dob' => NULL,
            'education' => '<p><span style="color: rgb(51, 51, 51); font-family: Roboto, sans-serif;">বি এস সি (অনার্স), এম এস সি ।</span><br></p>',
                'email' => 'mukulphy@gmail.com',
                'father_name' => 'মোহাম্মদ আমজাদ হূসাইন খান',
                'gender' => 'Male',
                'id' => 133,
                'image' => 'teacherstaff_image/6630.jpg',
                'join_date' => NULL,
                'mobile' => '01818394808',
                'mother_name' => 'রোকেয়া বেগম',
                'mpo_date' => NULL,
                'name' => 'মো: মুকুল হুসাইন খান',
                'nid' => 'null',
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Unmarried',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'blood' => NULL,
                'created_at' => NULL,
                'department_id' => 35,
                'designation' => 'প্রভাষক,পদার্থ বিজ্ঞান বিভাগ',
                'dob' => NULL,
            'education' => '<p style="margin-bottom: 10px; color: rgb(51, 51, 51); font-family: Roboto, sans-serif;">এস এস সি(১ম), এইচ এস সি (১ম), বি এস সি (অনার্স-২য়),</p><p style="margin-bottom: 10px; color: rgb(51, 51, 51); font-family: Roboto, sans-serif;">এম এস সি-২য় ।</p>',
                'email' => 'pranabdas30@yahoo.com',
                'father_name' => NULL,
                'gender' => 'Male',
                'id' => 134,
                'image' => 'teacherstaff_image/5153.jpg',
                'join_date' => NULL,
                'mobile' => '01915-794161',
                'mother_name' => NULL,
                'mpo_date' => NULL,
                'name' => 'প্রনব চন্দ্র দাস',
                'nid' => NULL,
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Unmarried',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'blood' => NULL,
                'created_at' => NULL,
                'department_id' => 36,
                'designation' => 'সহকারী অধ্যাপক',
                'dob' => NULL,
                'education' => '<p>Null</p>',
                'email' => 'akterhossain86@gmail.com',
                'father_name' => NULL,
                'gender' => 'Male',
                'id' => 135,
                'image' => 'teacherstaff_image/3148.jpg',
                'join_date' => NULL,
                'mobile' => '01711243886',
                'mother_name' => NULL,
                'mpo_date' => NULL,
                'name' => 'মোহাম্মদ আকতার হোসেন',
                'nid' => NULL,
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Unmarried',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'blood' => NULL,
                'created_at' => NULL,
                'department_id' => 36,
                'designation' => 'প্রভাষক',
                'dob' => NULL,
                'education' => '<p>Null</p>',
                'email' => 'mubasera06@gmail.com',
                'father_name' => NULL,
                'gender' => 'Female',
                'id' => 136,
                'image' => 'teacherstaff_image/2767.png',
                'join_date' => NULL,
                'mobile' => '01917961306',
                'mother_name' => NULL,
                'mpo_date' => NULL,
                'name' => 'মোবাশ্বেরা আক্তার',
                'nid' => NULL,
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Unmarried',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'blood' => NULL,
                'created_at' => NULL,
                'department_id' => 36,
                'designation' => 'প্রভাষক',
                'dob' => NULL,
                'education' => '<p>Null</p>',
                'email' => 'kamrunnahar96@gmail.com',
                'father_name' => NULL,
                'gender' => 'Female',
                'id' => 137,
                'image' => 'teacherstaff_image/8188.png',
                'join_date' => NULL,
                'mobile' => '01813668396',
                'mother_name' => NULL,
                'mpo_date' => NULL,
                'name' => 'কামরুল নাহার',
                'nid' => NULL,
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Unmarried',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'blood' => NULL,
                'created_at' => NULL,
                'department_id' => 37,
            'designation' => 'সহযোগী অধ্যাপক(সমাজকল্যান)',
                'dob' => NULL,
            'education' => '<p><span style="color: rgb(51, 51, 51); font-family: Roboto, sans-serif;">বি এ (অনার্স), এম এস এস</span><br></p>',
                'email' => 'www.fapintu1966@gmail.com',
                'father_name' => NULL,
                'gender' => 'Male',
                'id' => 138,
                'image' => 'teacherstaff_image/5355.jpg',
                'join_date' => NULL,
                'mobile' => '01711229607',
                'mother_name' => NULL,
                'mpo_date' => NULL,
                'name' => 'মো: ফখরুল আমিন',
                'nid' => NULL,
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Married',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'blood' => NULL,
                'created_at' => NULL,
                'department_id' => 37,
                'designation' => 'সহকারী অধ্যাপক',
                'dob' => NULL,
                'education' => '<p>Null</p>',
                'email' => 'foridalom18@gmail.com',
                'father_name' => NULL,
                'gender' => 'Male',
                'id' => 139,
                'image' => 'teacherstaff_image/5626.jpg',
                'join_date' => NULL,
                'mobile' => '01711479218',
                'mother_name' => NULL,
                'mpo_date' => NULL,
                'name' => 'ফরিদ আলম ভূঁঞা',
                'nid' => NULL,
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Married',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'blood' => NULL,
                'created_at' => NULL,
                'department_id' => 36,
                'designation' => 'প্রভাষক',
                'dob' => NULL,
                'education' => '<p>Null</p>',
                'email' => 'asadurjaman64@gmail.com',
                'father_name' => NULL,
                'gender' => 'Male',
                'id' => 140,
                'image' => 'teacherstaff_image/9333.jpg',
                'join_date' => NULL,
                'mobile' => '01912654764',
                'mother_name' => NULL,
                'mpo_date' => NULL,
                'name' => 'মোঃ আসাদুজ্জামান',
                'nid' => NULL,
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Unmarried',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'blood' => NULL,
                'created_at' => NULL,
                'department_id' => 44,
                'designation' => 'প্রভাষক, প্রাণিবিদ্যা বিভাগ',
                'dob' => NULL,
            'education' => '<p><span style="color: rgb(51, 51, 51); font-family: Roboto, sans-serif;">BSc (Honours),M.Phil(Zoology)</span><br></p>',
                'email' => 'motaharcu07@gmail.com',
                'father_name' => NULL,
                'gender' => 'Male',
                'id' => 141,
                'image' => 'teacherstaff_image/3890.jpg',
                'join_date' => NULL,
                'mobile' => '01712607191',
                'mother_name' => NULL,
                'mpo_date' => NULL,
                'name' => 'মুহাম্মদ মোতাহার হোসাইন',
                'nid' => NULL,
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Unmarried',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '1',
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'blood' => NULL,
                'created_at' => NULL,
                'department_id' => NULL,
                'designation' => 'হিসাব রক্ষক',
                'dob' => NULL,
                'education' => '<p>&nbsp;Null</p>',
                'email' => 'fenigovcollege@yahoo.com',
                'father_name' => NULL,
                'gender' => 'Male',
                'id' => 142,
                'image' => 'public/otherimage/1757920985797310.jpg',
                'join_date' => NULL,
                'mobile' => '018186459831',
                'mother_name' => NULL,
                'mpo_date' => NULL,
                'name' => 'এ.এম মোমেন হোসেন শিকদার',
                'nid' => NULL,
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Married',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '2',
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'blood' => NULL,
                'created_at' => NULL,
                'department_id' => NULL,
                'designation' => 'মেকানিক কাম ইলেকট্রিশিয়ান',
                'dob' => NULL,
                'education' => '<p>Null</p>',
                'email' => 'fenigovcollege@yahoo.com',
                'father_name' => NULL,
                'gender' => 'Male',
                'id' => 143,
                'image' => 'public/otherimage/1757921094961162.jpg',
                'join_date' => NULL,
                'mobile' => '01830074134',
                'mother_name' => NULL,
                'mpo_date' => NULL,
                'name' => 'মো : হাবিবুর রহমান',
                'nid' => NULL,
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Married',
                'religion' => 'Islam',
                'status' => NULL,
                'type' => '2',
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'blood' => NULL,
                'created_at' => NULL,
                'department_id' => NULL,
                'designation' => 'গ্রন্থাগারিক',
                'dob' => NULL,
                'education' => '<p>Null</p>',
                'email' => 'fenigovcollege@yahoo.com',
                'father_name' => NULL,
                'gender' => 'Male',
                'id' => 144,
                'image' => 'public/otherimage/1757921171282764.jpg',
                'join_date' => NULL,
                'mobile' => '01920821320',
                'mother_name' => NULL,
                'mpo_date' => NULL,
                'name' => 'বাবুল চন্দ্র সাহা',
                'nid' => NULL,
                'parmanent_address' => 'ফেনী',
                'present_address' => 'ফেনী',
                'relationship' => 'Married',
                'religion' => 'Hindu',
                'status' => NULL,
                'type' => '2',
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}